# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f7d099dbf11640101f76249e7cbba0d14e667e0de6c5ea38df825dcb1e35faf27d6673666109c4aaf9b411c106822ba82cc5c7c4c4559780684ce508e25899

test:
  secret_key_base: 6748301f87146260399dad7d6f8bf0faea2a1b4256aa0771b4e7a27be08cf6535b3c21f831f4834afeac578355f5f97a69d03cd64936d37ac97b76362da9a268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
